name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - custom
      custom_version:
        description: 'Custom version (if version is custom)'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install release builder dependencies
      run: |
        npm install -g @vscode/vsce
    
    - name: Build release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      run: node build-release.js --version=none --skip-tests --skip-lint --no-git
    
    - name: Build release (manual dispatch - patch)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version == 'patch'
      run: |
        node build-release.js --version=patch --skip-tests --skip-lint --no-git
    
    - name: Build release (manual dispatch - minor)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version == 'minor'
      run: |
        node build-release.js --version=minor --skip-tests --skip-lint --no-git
    
    - name: Build release (manual dispatch - major)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version == 'major'
      run: |
        node build-release.js --version=major --skip-tests --skip-lint --no-git
    
    - name: Build release (manual dispatch - custom)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version == 'custom'
      run: |
        npm version ${{ github.event.inputs.custom_version }} --no-git-tag-version
        node build-release.js --version=none --skip-tests --skip-lint --no-git
    
    - name: Get version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.version }}" == "custom" ]]; then
          echo "version=${{ github.event.inputs.custom_version }}" >> $GITHUB_OUTPUT
        else
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          releases/url-pinger-${{ steps.version.outputs.version }}.vsix
          releases/release-notes-${{ steps.version.outputs.version }}.md
          CHANGELOG.md
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: URL Pinger v${{ steps.version.outputs.version }}
        body_path: releases/release-notes-${{ steps.version.outputs.version }}.md
        draft: false
        prerelease: false
    
    - name: Upload VSIX to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: releases/url-pinger-${{ steps.version.outputs.version }}.vsix
        asset_name: url-pinger-${{ steps.version.outputs.version }}.vsix
        asset_content_type: application/zip
